### ISSUE TITLE
Orange area and Topic titles

### ISSUE THREAD

**Issue by onword** [DigiDago/moodle-format_softcourse#89]
### Subject of the issue/enhancement/features
Moodle 3.10.3
Soft Course 3.11rc1.2
When viewing a course page on cellphone the orange area where an image can be placed is being squished, and the topic titles are being truncated instead of wrapping.

### Steps to reproduce
Chose Soft Course format and viewed course on mobile (Redmi K40 cellphone in this case)

### Expected behaviour
Orange area should be wider to accommodate images, title should wrap instead of being truncated if possible.

### Actual behaviour
Orange area is squished, topic title is truncated

### Screenshots (if you can)
![IMG_20210606_093913](https://user-images.githubusercontent.com/78563574/120926581-7cc62600-c6ab-11eb-96eb-4a0773a59856.jpg)

The full title topics of the sections above being truncated are:
Hiragana - pronunciation and reading
Hiragana - printable charts and writing practice
Katakana - pronunciation and reading
Katakana - printable charts and writing practice

**Comment by CrymSonir** [comment]
About the orange areas this is the default behavior of the plugin, we hide the images in mobile view because the display would be problematic.

However indeed the truncated text is a bug, I will report this issue and we will look at it as soon as possible :)

**Comment by onword** [comment]
Thank you!

**Comment by CrymSonir** [comment]
Hello,

Regarding the subject of truncated titles/summary content, I inform you of the decision we have taken.

We cannot display them entirely because a content area below does not allow us to display them on two lines.

In addition the "cards" have a maximum fixed height that we do not plan to increase for now.

To improve the visual, however, we will automatically add "..." to symbolize that the text exceeds the container.

example:
<img width="952" alt="Capture d’écran 2021-06-10 à 15 59 33" src="https://user-images.githubusercontent.com/8981947/121539129-ad88c100-ca05-11eb-8804-7c61963f554d.png">

This correction will arrive soon with the upgrade of the plugin :)

Best regards,
Sylvain - Pimenko Team.

**Comment by onword** [comment]
Thanks Sylvain, it’s a good fix in the meantime. Much appreciated.

I also put in a report for the Course Module Navigation block plugin, but have not received any reply. Do you look after that plugin also? I do not know if it is something that needs to be fixed in Course Module Navigation, or by the Onetopic course format creator… or both parties.

Thanks again. These are great plugins.

Raymond
